version: '3'
services:
  proposta:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8081:8080
    environment:
      PROPOSTA_DATASOURCE_URL: "jdbc:mysql://db:3306/proposta"
      PROPOSTA_DATASOURCE_USERNAME: "userproposta"
      PROPOSTA_DATASOURCE_PASSWORD: "password"
      SERVICO_ANALISE: "http://analise:9999/"
      SERVICO_CARTOES: "http://contas:8888/"
      HEALTH_ENDPOINT_EXPOSURE_INCLUDE: "health"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: proposta
      MYSQL_USER: userproposta
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  mysql-volume:
  
